### PR TITLE
Es set public vars

### PR DESCRIPTION
**Pull request by EslamSalem95**
Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by Jeehut** [comment]
@EslamSalem95 Thank you for the contribution. But could you also give some more context, please? Why do you need these implementation details to be public?

**Comment by Jeehut** [comment]
@EslamSalem95 Here's a quick reminder to give an explanation about the PR. If no explanation is provided, I will close this.

**Comment by EslamSalem95** [comment]
@Jeehut  I apologize for not receiving your comments. The purpose of change has been discussed above.

**Comment by Jeehut** [comment]
@EslamSalem95 Thank you for the update. Feel free to open another PR with the changes. But to be honest, I would prefer if instead of making these internal APIs public, to simply add your multi-part request implementation to the project. This way everyone would profit from that and it could be improved by the community over time.

**Comment by EslamSalem95** [comment]
@Jeehut It is possible for sure, I will create a new pull request with multipart functions.

**Pull request closed without merging**
